# Site settings
title: "Only the Best"
description: "site description goes here"

baseurl: "https://lvuch.github.io/OnlyTheBest"

# Build settings
# markdown: kramdown
# sass:
#   sass_dir: _sass
#   style: compressed