# Site settings
title: "Only the Best"
description: "site description goes here"

url: "https://lvuch.github.io/OnlyTheBest"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed